/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perbaikan_uts_3a_22090153;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tengku
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_nim = new javax.swing.JLabel();
        display_nim = new javax.swing.JTextField();
        lbl_nama = new javax.swing.JLabel();
        display_nama = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        display_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, -1));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, -1));

        jLabel1.setText("NIM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lbl_nim.setText("NIM");
        getContentPane().add(lbl_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        display_nim.setEditable(false);
        display_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_nimActionPerformed(evt);
            }
        });
        getContentPane().add(display_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 170, -1));

        lbl_nama.setText("Nama");
        getContentPane().add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        display_nama.setEditable(false);
        getContentPane().add(display_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, -1));

        lbl_email.setText("Email");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        display_email.setEditable(false);
        getContentPane().add(display_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        
        String nim = txt_input.getText();
        String q = "SELECT * FROM `table_mahasiswa` WHERE NIM =" + nim + ";";
        try {
            Connection k = Koneksi.Go();
            Statement s;
            s = k.createStatement();
            ResultSet r = s.executeQuery(q);

            if (!r.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null, "NIM not found in the database", "Error", JOptionPane.ERROR_MESSAGE);
            } else {                
                while (r.next()) {
                    int id_db = r.getInt("id");
                    int nim_db = r.getInt("NIM");
                    String nama_db = r.getString("NAMA");
                    String email_db = r.getString("EMAIL");
                    display_nim.setText(Integer.toString(nim_db));
                    display_nama.setText(nama_db);
                    display_email.setText(email_db);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void display_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_nimActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_display_nimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JTextField display_email;
    private javax.swing.JTextField display_nama;
    private javax.swing.JTextField display_nim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nim;
    private javax.swing.JTextField txt_input;
    // End of variables declaration//GEN-END:variables
}
